### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by xiaoao** [jlcool/aliossflutter#1]
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':aliossflutter:debugCompileClasspath'.
> Could not determine artifacts for com.aliyun.dpa:oss-android-sdk:2.9.2
   > Could not get resource 'https://jcenter.bintray.com/com/aliyun/dpa/oss-android-sdk/2.9.2/oss-android-sdk-2.9.2.aar'.
      > Could not HEAD 'https://jcenter.bintray.com/com/aliyun/dpa/oss-android-sdk/2.9.2/oss-android-sdk-2.9.2.aar'.
         > Connect to d29vzk4ow07wi7.cloudfront.net:443 [d29vzk4ow07wi7.cloudfront.net/54.192.84.168, d29vzk4ow07wi7.cloudfront.net/54.192.84.173, d29vzk4ow07wi7.cloudfront.net/54.192.84.128, d29vzk4ow07wi7.cloudfront.net/54.192.84.6] failed: Read timed out

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by jlcool** [comment]
需要翻墙？看错误是无法连接不能下载文件 阿里云的sdk

**Comment by xiaoao** [comment]
ok
