### ISSUE TITLE
文档写的太乱了···

### ISSUE THREAD

**Issue by sunshineinwater** [jlcool/aliossflutter#10]
看了半天，关键变量的含义模棱两可的，难受啊。
可能是个好东西，研究半天又用不上。。
可否规范一下代码注释和文档啊···

**Comment by jlcool** [comment]
你可以先看下oss官方文档 https://help.aliyun.com/document_detail/31883.html?spm=a2c4g.11186623.2.7.418158a85m976L#concept-ptc-g24-tdb
