### ISSUE TITLE
升级最新版已经用不了了

### ISSUE THREAD

**Issue by liuchuancong** [jlcool/aliossflutter#11]
W/System.err(26694): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: oss-android-api-thread
W/System.err(26694): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:794)
W/System.err(26694): 	at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:684)
W/System.err(26694): 	at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:80)
W/System.err(26694): 	at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:189)
W/System.err(26694): 	at io.flutter.view.FlutterNativeView.send(FlutterNativeView.java:155)
W/System.err(26694): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:98)
W/System.err(26694): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:84)
W/System.err(26694): 	at com.jlcool.aliossflutter.AliossflutterPlugin$3.onProgress(AliossflutterPlugin.java:229)
W/System.err(26694): 	at com.jlcool.aliossflutter.AliossflutterPlugin$3.onProgress(AliossflutterPlugin.java:220)
W/System.err(26694): 	at com.alibaba.sdk.android.oss.network.ProgressTouchableRequestBody.writeTo(ProgressTouchableRequestBody.java:65)
W/System.err(26694): 	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:72)
W/System.err(26694): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
W/System.err(26694): 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
W/System.err(26694): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
W/System.err(26694): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
W/System.err(26694): 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
W/System.err(26694): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
W/System.err(26694): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
W/System.err(26694): 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
W/System.err(26694): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
W/System.err(26694): 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
W/System.err(26694): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
W/System.err(26694): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
W/System.err(26694): 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
W/System.err(26694): 	at okhttp3.RealCall.execute(RealCall.java:77)
W/System.err(26694): 	at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:177)
W/System.err(26694): 	at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:44)
W/System.err(26694): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err(26694): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
W/System.err(26694): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
W/System.err(26694): 	at java.lang.Thread.run(Thread.java:764)

**Comment by jlcool** [comment]
你可以先试试将插件android代码中的_result.success删除

**Comment by jlcool** [comment]
已修复
