### ISSUE TITLE
sts server的调用，应该由调用者实现，而不是库自行实现

### ISSUE THREAD

**Issue by codecomeon** [jlcool/aliossflutter#15]
由外部传入一个Future，返回指定格式的参数，而不是由你自己实现sts server的调用，可以参考腾讯云cos的sdk。

https://github.com/tencentyun/cos-js-sdk-v5

getAuthorization

**Comment by jlcool** [comment]
都可以吧，有什么特别需求

**Comment by codecomeon** [comment]
这里遇到的问题是，sts server的调用如果库自己实现的话，请求体、响应体的定义都做不了，这个灵活性太低了，不如通过库通过Future来获取sts参数

**Comment by jlcool** [comment]
sdk的用法是这样的
```
// 推荐使用OSSAuthCredentialsProvider。token过期可以及时更新。
OSSCredentialProvider credentialProvider = new OSSAuthCredentialsProvider(stsServer);
```
只接收STS应用服务器地址参数，有没有别的方法没研究过
