### ISSUE TITLE
stsserver端日志显示是取到了securitytoken的，为什么flutter里面总报这个

### ISSUE THREAD

**Issue by xiaoao** [jlcool/aliossflutter#2]
W/System.err(24659): org.json.JSONException: No value for Data
W/System.err(24659):    at org.json.JSONObject.get(JSONObject.java:392)
W/System.err(24659):    at org.json.JSONObject.getString(JSONObject.java:553)
W/System.err(24659):    at com.jlcool.aliossflutter.AliossflutterPlugin$1.getFederationToken(AliossflutterPlugin.java:110)
W/System.err(24659):    at com.alibaba.sdk.android.oss.common.auth.OSSFederationCredentialProvider.getValidFederationToken(OSSFederationCredentialProvider.java:30)
W/System.err(24659):    at com.alibaba.sdk.android.oss.common.utils.OSSUtils.signRequest(OSSUtils.java:664)
W/System.err(24659):    at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:86)
W/System.err(24659):    at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:243)
W/System.err(24659):    at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:243)
W/System.err(24659):    at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:44)
W/System.err(24659):    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err(24659):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err(24659):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err(24659):    at java.lang.Thread.run(Thread.java:764)
W/System.err(24659): com.alibaba.sdk.android.oss.ClientException: Can't get a federation token
W/System.err(24659): [ErrorMessage]: Can't get a federation token
W/System.err(24659):    at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:200)
W/System.err(24659):    at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:243)
W/System.err(24659):    at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:243)
W/System.err(24659):    at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:44)
W/System.err(24659):    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err(24659):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err(24659):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err(24659):    at java.lang.Thread.run(Thread.java:764)
W/System.err(24659): Caused by: java.io.IOException: Can't get a federation token
W/System.err(24659):    at com.alibaba.sdk.android.oss.common.utils.OSSUtils.signRequest(OSSUtils.java:667)
W/System.err(24659):    at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:86)
W/System.err(24659):    ... 7 more

**Comment by jlcool** [comment]
是不是init的时候写了cryptkey，如果不用3DES加密，cryptkey不要写
