### ISSUE TITLE
使用上传地址和凭证上传

### ISSUE THREAD

**Issue by leielyq** [jlcool/aliossflutter#26]
请问支持这个方式上传吗？
https://www.alibabacloud.com/help/zh/doc-detail/99889.htm?spm=a2c63.p38356.b99.369.4e274408h5QYEu

**Comment by jlcool** [comment]
这个是oss不是视频点播插件

**Comment by leielyq** [comment]
呀，我只想用这个上传，应该可以把，我也不知道

**Comment by leielyq** [comment]
@jlcool 只是上传文件  可以不

**Comment by jlcool** [comment]
可以传到阿里云oss，文档https://help.aliyun.com/document_detail/31883.html?spm=5176.8465980.entries.3.4e70145076FYLa

**Comment by leielyq** [comment]
@jlcool 好的，谢谢。太可惜了，这两个产品不能通用
