### ISSUE TITLE
servercallback 为什么一直为空

### ISSUE THREAD

**Issue by gaoyong06** [jlcool/aliossflutter#27]
作者你好，我把aliossflutter集成后，上传图片都是ok的，但是返回值 servercallback 一直是null
因为我们oss的服务端接口在已有的Android app上工作都是ok的，所有我确认我们servercallback 会返回一个Json串，但是使用aliossflutter后，我理解应该在data.servercallback 拿到一个字符串(json串)，但是现在是个null, 不知应该从哪里查起？

`
alioss.responseFromUpload.listen((data) {
        print("data.success：${data.success}");
        print("data.key：${data.key}");
        print("data.msg：${data.msg}");
        print("data.servercallback：${data.servercallback}");
}

`
----------下面是打印结果-----------
flutter: data.success：true
flutter: data.key：2020/05/12/898cadda544e668da67d60a4b6188c23.JPG
flutter: data.msg：null
flutter: data.servercallback：null

**Comment by jlcool** [comment]
是这么上传的吗alioss.upload("bucket", file.path, "key",callbackBody: Config.callbackBody,callbackBodyType: Config.callbackBodyType,callbackHost: Config.callbackHost,callbackUrl: Config.callbackUrl,callbackVars: Config.callbackVars);

**Comment by gaoyong06** [comment]
> 是这么上传的吗alioss.upload("bucket", file.path, "key",callbackBody: Config.callbackBody,callbackBodyType: Config.callbackBodyType,callbackHost: Config.callbackHost,callbackUrl: Config.callbackUrl,callbackVars: Config.callbackVars);

是，参数验证了好几次，没有问题

**Comment by gaoyong06** [comment]
我看了一会日志，发现图片确定上传到oss了，但是oss没有回调我们的接口地址

**Comment by jlcool** [comment]
着急的话自己先看下代码吧

**Comment by gaoyong06** [comment]
测试了半天可以肯定：
1. 我写的callback参数和调用方法是没有问题的
2. oss确实没用调用服务器的callbackUrl
3. servercallback 确实没有返回值

--
没写过插件，所有看代码看的也是迷糊

**Comment by gaoyong06** [comment]
兄弟，有时间一起调试下嘛，卡这了😁

**Comment by jlcool** [comment]
测试了下没问题，你看看官方文档 https://help.aliyun.com/document_detail/31853.html?spm=a2c4g.11186623.2.8.26fddfcbbatFhg#concept-ywd-dlb-5db ，注意是post。如果还有问题，请提供个例子

**Comment by gaoyong06** [comment]
> 测试了下没问题，你看看官方文档 https://help.aliyun.com/document_detail/31853.html?spm=a2c4g.11186623.2.8.26fddfcbbatFhg#concept-ywd-dlb-5db ，注意是post。如果还有问题，请提供个例子

感谢回复，嗯嗯，这个官方文档我确实熟读过，而且我自己用官方的POST提交的示例，在现在的项目里面也实现了，callback都是正常工作的，比较不爽的是，我的实现比较简单，没有获取上传进度之类的，看到aliossflutter比较完善，所以想废弃自己实现的，使用aliossflutter来处理这个业务，我在核查一下，非常感谢
