### ISSUE TITLE
作者你好

### ISSUE THREAD

**Issue by jiaoheng1** [jlcool/aliossflutter#3]
![Uploading image.png…]()
这几个参数是什么意思呀 对应的什么  非常需要你的帮助 谢谢您

**Comment by jlcool** [comment]
看不到图片

**Comment by luojuan5** [comment]
![image](https://user-images.githubusercontent.com/44315066/55403530-9d087080-5588-11e9-8483-042d2dad4cef.png)

**Comment by luojuan5** [comment]
您好，这些参数对应什么？希望能得到您的帮助

**Comment by jlcool** [comment]
你需要看下oss的文档，还有我们项目里的example
