### ISSUE TITLE
clone下来的是空文件夹

### ISSUE THREAD

**Issue by cmz-one** [jlcool/aliossflutter#31]
pub上只有0.0.4版本，打apk包会出错，切换到到github最新的源后，克隆下来的库文件夹是空的。

Could not find a file named "pubspec.yaml" in "D:\flutter\.pub-cache\git\aliossflutter-94ebf9aa0a4f4e0a57fd19b090748acd579e500b".
pub get failed (66; Could not find a file named "pubspec.yaml" in "D:\flutter\.pub-cache\git\aliossflutter-94ebf9aa0a4f4e0a57fd19b090748acd579e500b".)

**Comment by jlcool** [comment]
你要不试试clone到其他目录后在pubspec.yaml中使用path配置
