### ISSUE TITLE
ios编译报错，android的编译使用没问题，用的是github上最新的可以自签名的插件

### ISSUE THREAD

**Issue by xindanci** [jlcool/aliossflutter#8]
Xcode's output:
↳
    In file included from /Users/cyc/.pub-cache/git/aliossflutter-615a996377e9769bbae4ccd7d0980e5ffe5e55d4/ios/Classes/AliossflutterPlugin.m:1:
    /Users/cyc/.pub-cache/git/aliossflutter-615a996377e9769bbae4ccd7d0980e5ffe5e55d4/ios/Classes/AliossflutterPlugin.h:2:9: fatal error: 'AliyunOSSiOS/OSSService.h' file not found
    #import <AliyunOSSiOS/OSSService.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

**Comment by jlcool** [comment]
是用的flutter build ios吗

**Comment by jlcool** [comment]
直接启动xcode没有pod install吧

**Comment by xindanci** [comment]
> 是用的flutter build ios吗

是的，我把插件单独用一个demo编译也是报同样的错误

**Comment by jlcool** [comment]
已添加pod依赖，现在可以了

**Comment by xindanci** [comment]
> 已添加pod依赖，现在可以了
现在运行会一直停留在
Launching lib/main.dart on iPhone XR in debug mode...
Running pod install...
这里，等了好久没有任何反应

**Comment by jlcool** [comment]
不确定是否是要访问外网安装oss，而你的网络被限制了

**Comment by xindanci** [comment]
> 不确定是否是要访问外网安装oss，而你的网络被限制了

应该不是网络的问题了，换了设备和网络，还上了梯子，都行不通，只要依赖这个插件就会出现这种情况，还有一个现象就是没有这个插件的时候两行代码执行速度非常快，依赖之后这两行代码的执行间隔会变大，不知道是什么原因

**Comment by xindanci** [comment]
> 不确定是否是要访问外网安装oss，而你的网络被限制了

你是应该是对的，确实需要安装oss，昨天公司电脑挂了一晚上，今天早上来可以编译了。不过这个下载过程是真的久，在家里弄的等了一个小时还没反应
